### ISSUE TITLE
v3.0.0 code?

### ISSUE THREAD

**Issue by Jonqora** [Gathouria/Adopt-Skin#1]
Hi! Would it be possible to push the newest v3.0.0 code here? I was hoping to fork it to investigate a possible bugfix.

**Comment by Gathouria** [comment]
Whoops, forgot that the 3.0 code was on a private repo! Give me a bit and I'll have that pushed over.

**Comment by Gathouria** [comment]
Now published under a new branch!

Some additional changes have been made to wild Horses that I had yet to publish to Nexus. They were the beginnings of a new feature I was working on but had yet to finish, related to ownership of Horses (and eventually Pets). This may help out in multiplayer!

Also added the ability to limit whether you are notified of a wild Horse's spawn location but still be notified of whether they spawned at all, as well as the ability to remove locations as potential wild Horse spawning locations.
